import { PageService } from './services/page.service';
import { BacklinkService } from './services/backlink.service';
import { PageAccessService } from './page-access/page-access.service';
import { CreatePageDto } from './dto/create-page.dto';
import { UpdatePageDto } from './dto/update-page.dto';
import { MovePageDto, MovePageToSpaceDto } from './dto/move-page.dto';
import { DeletePageDto, PageHistoryIdDto, PageIdDto, PageInfoDto } from './dto/page.dto';
import { PageHistoryService } from './services/page-history.service';
import { PaginationOptions } from "../../database/pagination/pagination-options";
import { User, Workspace } from "../../database/types/entity.types";
import { SidebarPageDto } from './dto/sidebar-page.dto';
import SpaceAbilityFactory from '../casl/abilities/space-ability.factory';
import { PageRepo } from "../../database/repos/page/page.repo";
import { RecentPageDto } from './dto/recent-page.dto';
import { CreatedByUserDto } from './dto/created-by-user.dto';
import { DuplicatePageDto } from './dto/duplicate-page.dto';
import { DeletedPageDto } from './dto/deleted-page.dto';
import { BacklinksListDto } from './dto/backlink.dto';
import { LabelService } from '../label/label.service';
import { AddLabelsDto, RemoveLabelDto } from '../label/dto/label.dto';
import { IAuditService } from '../../integrations/audit/audit.service';
export declare class PageController {
    private readonly pageService;
    private readonly pageRepo;
    private readonly pageHistoryService;
    private readonly spaceAbility;
    private readonly pageAccessService;
    private readonly backlinkService;
    private readonly labelService;
    private readonly auditService;
    constructor(pageService: PageService, pageRepo: PageRepo, pageHistoryService: PageHistoryService, spaceAbility: SpaceAbilityFactory, pageAccessService: PageAccessService, backlinkService: BacklinkService, labelService: LabelService, auditService: IAuditService);
    getPage(dto: PageInfoDto, user: User): Promise<{
        permissions: {
            canEdit: boolean;
            hasRestriction: boolean;
        };
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        metadata: string | number | boolean | import("../../database/types/db").JsonArray | import("../../database/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>;
    getPageLabels(dto: PageIdDto, pagination: PaginationOptions, user: User): Promise<{
        items: {
            type: string;
            id: string;
            workspaceId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        }[];
        meta: {
            limit: number;
            hasNextPage: boolean;
            hasPrevPage: boolean;
            nextCursor: string | null;
            prevCursor: string | null;
        };
    }>;
    addPageLabels(dto: AddLabelsDto, user: User, workspace: Workspace): Promise<{
        type: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
    }[]>;
    removePageLabel(dto: RemoveLabelDto, user: User): Promise<void>;
    getBacklinksCount(dto: PageIdDto, user: User): Promise<{
        incoming: number;
        outgoing: number;
    }>;
    getBacklinks(dto: BacklinksListDto, pagination: PaginationOptions, user: User): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        id: string;
        slugId: string;
        title: string | null;
        icon: string | null;
        spaceId: string;
        updatedAt: Date;
        space: {
            id: string;
            slug: string;
            name: string;
        };
    }, undefined>>;
    create(createPageDto: CreatePageDto, user: User, workspace: Workspace): Promise<{
        permissions: {
            canEdit: boolean;
            hasRestriction: boolean;
        };
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        metadata: string | number | boolean | import("../../database/types/db").JsonArray | import("../../database/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>;
    update(updatePageDto: UpdatePageDto, user: User): Promise<{
        permissions: {
            canEdit: boolean;
            hasRestriction: boolean;
        };
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        metadata: string | number | boolean | import("../../database/types/db").JsonArray | import("../../database/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>;
    delete(deletePageDto: DeletePageDto, user: User, workspace: Workspace): Promise<void>;
    restore(pageIdDto: PageIdDto, user: User, workspace: Workspace): Promise<{
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        metadata: string | number | boolean | import("../../database/types/db").JsonArray | import("../../database/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>;
    getRecentPages(recentPageDto: RecentPageDto, pagination: PaginationOptions, user: User): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        metadata: string | number | boolean | import("../../database/types/db").JsonArray | import("../../database/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>>;
    getCreatedByPages(dto: CreatedByUserDto, pagination: PaginationOptions, user: User): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        metadata: string | number | boolean | import("../../database/types/db").JsonArray | import("../../database/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>>;
    getDeletedPages(deletedPageDto: DeletedPageDto, pagination: PaginationOptions, user: User): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        metadata: string | number | boolean | import("../../database/types/db").JsonArray | import("../../database/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>>;
    getPageHistory(dto: PageIdDto, pagination: PaginationOptions, user: User): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        id: string;
        workspaceId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        content: import("../../database/types/db").JsonValue;
        slug: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        icon: string;
        lastUpdatedById: string;
        slugId: string;
        pageId: string;
        version: number;
    }>>;
    getPageHistoryInfo(dto: PageHistoryIdDto, user: User): Promise<{
        id: string;
        workspaceId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        content: import("../../database/types/db").JsonValue;
        slug: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        icon: string;
        lastUpdatedById: string;
        slugId: string;
        pageId: string;
        version: number;
    }>;
    getSidebarPages(dto: SidebarPageDto, pagination: PaginationOptions, user: User): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<Partial<{
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        metadata: string | number | boolean | import("../../database/types/db").JsonArray | import("../../database/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }> & {
        hasChildren: boolean;
    }>>;
    movePageToSpace(dto: MovePageToSpaceDto, user: User): Promise<void>;
    duplicatePage(dto: DuplicatePageDto, user: User): Promise<any>;
    movePage(dto: MovePageDto, user: User): Promise<void>;
    getPageBreadcrumbs(dto: PageIdDto, user: User): Promise<{
        id: string;
        title: string;
        deletedAt: Date;
        spaceId: string;
        icon: string;
        parentPageId: string;
        position: string;
        slugId: string;
        hasChildren: import("kysely").SqlBool;
    }[]>;
}
