import type { Node as PMNode } from '@tiptap/pm/model';
import type { Decoration, DecorationSource, NodeView } from '@tiptap/pm/view';
import type { Editor } from '@tiptap/core';
export type ResizableNodeViewDirection = 'top' | 'right' | 'bottom' | 'left' | 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
export type ResizableNodeDimensions = {
    width: number;
    height: number;
};
export type ResizableNodeViewOptions = {
    element: HTMLElement;
    contentElement?: HTMLElement;
    node: PMNode;
    editor: Editor;
    getPos: () => number | undefined;
    onResize?: (width: number, height: number) => void;
    onCommit: (width: number, height: number) => void;
    onUpdate: NodeView['update'];
    options?: {
        directions?: ResizableNodeViewDirection[];
        min?: Partial<ResizableNodeDimensions>;
        max?: Partial<ResizableNodeDimensions>;
        preserveAspectRatio?: boolean;
        className?: {
            container?: string;
            wrapper?: string;
            handle?: string;
            resizing?: string;
        };
        createCustomHandle?: (direction: ResizableNodeViewDirection) => HTMLElement;
    };
};
export declare class ResizableNodeView {
    node: PMNode;
    editor: Editor;
    element: HTMLElement;
    contentElement?: HTMLElement;
    container: HTMLElement;
    wrapper: HTMLElement;
    getPos: () => number | undefined;
    onResize?: (width: number, height: number) => void;
    onCommit: (width: number, height: number) => void;
    onUpdate?: NodeView['update'];
    directions: ResizableNodeViewDirection[];
    minSize: ResizableNodeDimensions;
    maxSize?: Partial<ResizableNodeDimensions>;
    preserveAspectRatio: boolean;
    classNames: {
        container: string;
        wrapper: string;
        handle: string;
        resizing: string;
    };
    createCustomHandle?: (direction: ResizableNodeViewDirection) => HTMLElement;
    private initialWidth;
    private initialHeight;
    private aspectRatio;
    private isResizing;
    private activeHandle;
    private startX;
    private startY;
    private startWidth;
    private startHeight;
    private isShiftKeyPressed;
    private lastEditableState;
    private handleMap;
    constructor(options: ResizableNodeViewOptions);
    get dom(): HTMLElement;
    get contentDOM(): HTMLElement | null;
    private handleEditorUpdate;
    update(node: PMNode, decorations: readonly Decoration[], innerDecorations: DecorationSource): boolean;
    destroy(): void;
    createContainer(): HTMLDivElement;
    createWrapper(): HTMLDivElement;
    private createHandle;
    private positionHandle;
    private attachHandles;
    private removeHandles;
    private applyInitialSize;
    private handleResizeStart;
    private handleMouseMove;
    private handleTouchMove;
    private handleResize;
    private handleMouseUp;
    private handleKeyDown;
    private handleKeyUp;
    private calculateNewDimensions;
    private applyConstraints;
    private applyAspectRatio;
}
