import '@mantine/core/styles.css';
import '@mantine/spotlight/styles.css';
import '@mantine/tiptap/styles.css';

import type { Metadata } from 'next';
import { TanstackProvider } from '@/components/providers/tanstack-provider';
import CustomToaster from '@/components/ui/custom-toaster';
import { theme } from '@/app/theme';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <TanstackProvider>
            {children}
            <CustomToaster />
          </TanstackProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
