import { KyselyDB, KyselyTransaction } from "../../types/kysely.types";
import { DB, Users } from '@docmost/db/types/db';
import { InsertableUser, UpdatableUser, User } from "../../types/entity.types";
import { PaginationOptions } from '../../pagination/pagination-options';
import { ExpressionBuilder } from 'kysely';
import { NotificationSettingKey } from '../../../core/notification/notification.constants';
export declare class UserRepo {
    private readonly db;
    constructor(db: KyselyDB);
    baseFields: Array<keyof Users>;
    findById(userId: string, workspaceId: string, opts?: {
        includePassword?: boolean;
        includeUserMfa?: boolean;
        includeScimExternalId?: boolean;
        trx?: KyselyTransaction;
    }): Promise<User>;
    findByEmail(email: string, workspaceId: string, opts?: {
        includePassword?: boolean;
        includeUserMfa?: boolean;
        includeScimExternalId?: boolean;
        trx?: KyselyTransaction;
    }): Promise<User>;
    updateUser(updatableUser: UpdatableUser, userId: string, workspaceId: string, trx?: KyselyTransaction): Promise<import("kysely").UpdateResult[]>;
    updateLastLogin(userId: string, workspaceId: string): Promise<import("kysely").UpdateResult[]>;
    insertUser(insertableUser: InsertableUser, trx?: KyselyTransaction): Promise<User>;
    roleCountByWorkspaceId(role: string, workspaceId: string): Promise<number>;
    getUsersPaginated(workspaceId: string, pagination: PaginationOptions): Promise<import("@docmost/db/pagination/cursor-pagination").CursorPaginationResult<{
        password: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        role: string;
        name: string;
        settings: import("@docmost/db/types/db").JsonValue;
        email: string;
        invitedById: string;
        avatarUrl: string;
        deactivatedAt: Date;
        emailVerifiedAt: Date;
        lastActiveAt: Date;
        lastLoginAt: Date;
        locale: string;
        hasGeneratedPassword: boolean;
        scimExternalId: string;
        timezone: string;
    }, undefined>>;
    updatePreference(userId: string, prefKey: string, prefValue: string | boolean): Promise<{
        password: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        role: string;
        name: string;
        settings: import("@docmost/db/types/db").JsonValue;
        email: string;
        invitedById: string;
        avatarUrl: string;
        deactivatedAt: Date;
        emailVerifiedAt: Date;
        lastActiveAt: Date;
        lastLoginAt: Date;
        locale: string;
        hasGeneratedPassword: boolean;
        scimExternalId: string;
        timezone: string;
    }>;
    updateNotificationSetting(userId: string, settingKey: NotificationSettingKey, settingValue: boolean): Promise<{
        password: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        role: string;
        name: string;
        settings: import("@docmost/db/types/db").JsonValue;
        email: string;
        invitedById: string;
        avatarUrl: string;
        deactivatedAt: Date;
        emailVerifiedAt: Date;
        lastActiveAt: Date;
        lastLoginAt: Date;
        locale: string;
        hasGeneratedPassword: boolean;
        scimExternalId: string;
        timezone: string;
    }>;
    withUserMfa(eb: ExpressionBuilder<DB, 'users'>): import("kysely").AliasedRawBuilder<{
        id: string;
        createdAt: string;
        isEnabled: boolean;
        method: string;
    }, "mfa">;
}
