import { CreatePageDto, ContentFormat } from '../dto/create-page.dto';
import { ContentOperation, UpdatePageDto } from '../dto/update-page.dto';
import { PageRepo } from "../../../database/repos/page/page.repo";
import { PagePermissionRepo } from "../../../database/repos/page/page-permission.repo";
import { Page, User } from "../../../database/types/entity.types";
import type { JsonValue } from '@docmost/db/types/db';
import { PaginationOptions } from "../../../database/pagination/pagination-options";
import { CursorPaginationResult } from "../../../database/pagination/cursor-pagination";
import { KyselyDB } from "../../../database/types/kysely.types";
import { MovePageDto } from '../dto/move-page.dto';
import { AttachmentRepo } from "../../../database/repos/attachment/attachment.repo";
import { StorageService } from '../../../integrations/storage/storage.service';
import { Queue } from 'bullmq';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { CollaborationGateway } from '../../../collaboration/collaboration.gateway';
import { WatcherService } from '../../watcher/watcher.service';
import { TransclusionService } from '../transclusion/transclusion.service';
export declare class PageService {
    private pageRepo;
    private pagePermissionRepo;
    private attachmentRepo;
    private readonly db;
    private readonly storageService;
    private attachmentQueue;
    private aiQueue;
    private generalQueue;
    private eventEmitter;
    private collaborationGateway;
    private readonly watcherService;
    private readonly transclusionService;
    private readonly logger;
    constructor(pageRepo: PageRepo, pagePermissionRepo: PagePermissionRepo, attachmentRepo: AttachmentRepo, db: KyselyDB, storageService: StorageService, attachmentQueue: Queue, aiQueue: Queue, generalQueue: Queue, eventEmitter: EventEmitter2, collaborationGateway: CollaborationGateway, watcherService: WatcherService, transclusionService: TransclusionService);
    findById(pageId: string, includeContent?: boolean, includeYdoc?: boolean, includeSpace?: boolean): Promise<Page>;
    create(userId: string, workspaceId: string, createPageDto: CreatePageDto): Promise<Page>;
    nextPagePosition(spaceId: string, parentPageId?: string): Promise<string>;
    update(page: Page, updatePageDto: UpdatePageDto, user: User): Promise<Page>;
    updatePageContent(pageId: string, content: string | object, operation: ContentOperation, format: ContentFormat, user: User): Promise<void>;
    getSidebarPages(spaceId: string, pagination: PaginationOptions, pageId?: string, userId?: string, spaceCanEdit?: boolean): Promise<CursorPaginationResult<Partial<Page> & {
        hasChildren: boolean;
    }>>;
    movePageToSpace(rootPage: Page, spaceId: string, userId: string): Promise<{
        childPageIds: string[];
    }>;
    duplicatePage(rootPage: Page, targetSpaceId: string | undefined, authUser: User): Promise<{
        hasChildren: boolean;
        childPageIds: string[];
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: JsonValue;
        metadata: string | number | boolean | import("@docmost/db/types/db").JsonArray | import("@docmost/db/types/db").JsonObject;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>;
    movePage(dto: MovePageDto, movedPage: Page): Promise<void>;
    getPageBreadCrumbs(childPageId: string): Promise<{
        id: string;
        title: string;
        deletedAt: Date;
        spaceId: string;
        icon: string;
        parentPageId: string;
        position: string;
        slugId: string;
        hasChildren: import("kysely").SqlBool;
    }[]>;
    getRecentSpacePages(spaceId: string, userId: string, pagination: PaginationOptions): Promise<CursorPaginationResult<Page>>;
    getRecentPages(userId: string, pagination: PaginationOptions): Promise<CursorPaginationResult<Page>>;
    getCreatedByPages(creatorId: string, requestingUserId: string, pagination: PaginationOptions, spaceId?: string): Promise<CursorPaginationResult<Page>>;
    getDeletedSpacePages(spaceId: string, userId: string, pagination: PaginationOptions): Promise<CursorPaginationResult<Page>>;
    forceDelete(pageId: string, workspaceId: string): Promise<void>;
    removePage(pageId: string, userId: string, workspaceId: string): Promise<void>;
    private parseProsemirrorContent;
    private filterAccessibleTreePages;
}
