import { AttachmentService } from './services/attachment.service';
import { FastifyReply, FastifyRequest } from 'fastify';
import { User, Workspace } from "../../database/types/entity.types";
import { StorageService } from '../../integrations/storage/storage.service';
import { AttachmentType } from './attachment.constants';
import SpaceAbilityFactory from '../casl/abilities/space-ability.factory';
import WorkspaceAbilityFactory from '../casl/abilities/workspace-ability.factory';
import { PageRepo } from "../../database/repos/page/page.repo";
import { AttachmentRepo } from "../../database/repos/attachment/attachment.repo";
import { EnvironmentService } from '../../integrations/environment/environment.service';
import { TokenService } from '../auth/services/token.service';
import { AttachmentInfoDto, RemoveIconDto } from './dto/attachment.dto';
import { PageAccessService } from '../page/page-access/page-access.service';
import { IAuditService } from '../../integrations/audit/audit.service';
export declare class AttachmentController {
    private readonly attachmentService;
    private readonly storageService;
    private readonly workspaceAbility;
    private readonly spaceAbility;
    private readonly pageRepo;
    private readonly attachmentRepo;
    private readonly environmentService;
    private readonly tokenService;
    private readonly pageAccessService;
    private readonly auditService;
    private readonly logger;
    constructor(attachmentService: AttachmentService, storageService: StorageService, workspaceAbility: WorkspaceAbilityFactory, spaceAbility: SpaceAbilityFactory, pageRepo: PageRepo, attachmentRepo: AttachmentRepo, environmentService: EnvironmentService, tokenService: TokenService, pageAccessService: PageAccessService, auditService: IAuditService);
    uploadFile(req: any, res: FastifyReply, user: User, workspace: Workspace): Promise<never>;
    getFile(req: FastifyRequest, res: FastifyReply, user: User, workspace: Workspace, fileId: string, fileName?: string): Promise<never>;
    getPublicFile(req: FastifyRequest, res: FastifyReply, workspace: Workspace, fileId: string, fileName?: string, jwtToken?: string): Promise<never>;
    uploadAvatarOrLogo(req: any, res: FastifyReply, user: User, workspace: Workspace): Promise<never>;
    getLogoOrAvatar(res: FastifyReply, workspace: Workspace, attachmentType: AttachmentType, fileName?: string): Promise<never>;
    getAttachmentInfo(dto: AttachmentInfoDto, workspace: Workspace, user: User): Promise<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        tsv: string;
        spaceId: string;
        textContent: string;
        pageId: string;
        aiChatId: string;
        fileExt: string;
        fileName: string;
        filePath: string;
        fileSize: string;
        mimeType: string;
    }>;
    removeIcon(dto: RemoveIconDto, user: User, workspace: Workspace): Promise<void>;
    private sendFileResponse;
}
