import { WorkspaceService } from '../services/workspace.service';
import { UpdateWorkspaceDto } from '../dto/update-workspace.dto';
import { UpdateWorkspaceUserRoleDto } from '../dto/update-workspace-user-role.dto';
import { PaginationOptions } from "../../../database/pagination/pagination-options";
import { WorkspaceInvitationService } from '../services/workspace-invitation.service';
import { AcceptInviteDto, InvitationIdDto, InviteUserDto, RevokeInviteDto } from '../dto/invitation.dto';
import { User, Workspace } from "../../../database/types/entity.types";
import WorkspaceAbilityFactory from '../../casl/abilities/workspace-ability.factory';
import { FastifyReply } from 'fastify';
import { EnvironmentService } from '../../../integrations/environment/environment.service';
import { LicenseCheckService } from '../../../integrations/environment/license-check.service';
import { CheckHostnameDto } from '../dto/check-hostname.dto';
import { RemoveWorkspaceUserDto } from '../dto/remove-workspace-user.dto';
import { WorkspaceRepo } from "../../../database/repos/workspace/workspace.repo";
export declare class WorkspaceController {
    private readonly workspaceService;
    private readonly workspaceInvitationService;
    private readonly workspaceAbility;
    private readonly workspaceRepo;
    private environmentService;
    private licenseCheckService;
    constructor(workspaceService: WorkspaceService, workspaceInvitationService: WorkspaceInvitationService, workspaceAbility: WorkspaceAbilityFactory, workspaceRepo: WorkspaceRepo, environmentService: EnvironmentService, licenseCheckService: LicenseCheckService);
    getWorkspacePublicInfo(req: any): Promise<{
        hostname: string;
        id: string;
        enforceSso: boolean;
        logo: string;
        name: string;
        authProviders: {
            id: string;
            type: string;
            name: string;
        }[];
    }>;
    getWorkspace(workspace: Workspace): Promise<{
        hostname: string;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        auditRetentionDays: number;
        trashRetentionDays: number;
        billingEmail: string;
        customDomain: string;
        defaultRole: string;
        defaultSpaceId: string;
        emailDomains: string[];
        enforceMfa: boolean;
        enforceSso: boolean;
        isScimEnabled: boolean;
        licenseKey: string;
        logo: string;
        name: string;
        plan: string;
        settings: import("../../../database/types/db").JsonValue;
        status: string;
        stripeCustomerId: string;
        trialEndAt: Date;
    }>;
    getEntitlements(workspace: Workspace): Promise<{
        cloud: boolean;
        tier: string;
        features: string[];
    }>;
    updateWorkspace(res: FastifyReply, dto: UpdateWorkspaceDto, user: User, workspace: Workspace): Promise<{
        hostname: string;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        auditRetentionDays: number;
        trashRetentionDays: number;
        billingEmail: string;
        customDomain: string;
        defaultRole: string;
        defaultSpaceId: string;
        emailDomains: string[];
        enforceMfa: boolean;
        enforceSso: boolean;
        isScimEnabled: boolean;
        logo: string;
        name: string;
        plan: string;
        settings: import("../../../database/types/db").JsonValue;
        status: string;
        stripeCustomerId: string;
        trialEndAt: Date;
    }>;
    getWorkspaceMembers(pagination: PaginationOptions, user: User, workspace: Workspace): Promise<import("../../../database/pagination/cursor-pagination").CursorPaginationResult<{
        password: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        role: string;
        name: string;
        settings: import("../../../database/types/db").JsonValue;
        email: string;
        invitedById: string;
        avatarUrl: string;
        deactivatedAt: Date;
        emailVerifiedAt: Date;
        lastActiveAt: Date;
        lastLoginAt: Date;
        locale: string;
        hasGeneratedPassword: boolean;
        scimExternalId: string;
        timezone: string;
    }>>;
    deactivateWorkspaceMember(dto: RemoveWorkspaceUserDto, user: User, workspace: Workspace): Promise<void>;
    activateWorkspaceMember(dto: RemoveWorkspaceUserDto, user: User, workspace: Workspace): Promise<void>;
    deleteWorkspaceMember(dto: RemoveWorkspaceUserDto, user: User, workspace: Workspace): Promise<void>;
    updateWorkspaceMemberRole(workspaceUserRoleDto: UpdateWorkspaceUserRoleDto, user: User, workspace: Workspace): Promise<{
        password: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        role: string;
        name: string;
        settings: import("../../../database/types/db").JsonValue;
        email: string;
        invitedById: string;
        avatarUrl: string;
        deactivatedAt: Date;
        emailVerifiedAt: Date;
        lastActiveAt: Date;
        lastLoginAt: Date;
        locale: string;
        hasGeneratedPassword: boolean;
        scimExternalId: string;
        timezone: string;
    }>;
    getInvitations(user: User, workspace: Workspace, pagination: PaginationOptions): Promise<import("../../../database/pagination/cursor-pagination").CursorPaginationResult<{
        id: string;
        workspaceId: string;
        createdAt: Date;
        role: string;
        email: string;
    }, undefined>>;
    getInvitationById(dto: InvitationIdDto, workspace: Workspace): Promise<{
        enforceSso: boolean;
        id: string;
        createdAt: Date;
        email: string;
    }>;
    inviteUser(inviteUserDto: InviteUserDto, user: User, workspace: Workspace): Promise<void>;
    resendInvite(revokeInviteDto: RevokeInviteDto, user: User, workspace: Workspace): Promise<void>;
    revokeInvite(revokeInviteDto: RevokeInviteDto, user: User, workspace: Workspace): Promise<void>;
    acceptInvite(acceptInviteDto: AcceptInviteDto, workspace: Workspace, res: FastifyReply): Promise<{
        requiresLogin: boolean;
    }>;
    checkHostname(checkHostnameDto: CheckHostnameDto): Promise<{
        hostname: string;
    }>;
    getInviteLink(inviteDto: InvitationIdDto, user: User, workspace: Workspace): Promise<{
        inviteLink: string;
    }>;
}
