import { Extension, afterUnloadDocumentPayload, onConfigurePayload, onLoadDocumentPayload } from '@hocuspocus/server';
import { BaseWebSocket, Configuration, CustomEvents, SerializedHTTPRequest } from './redis-sync.types';
export type { Pack, SerializedHTTPRequest } from './redis-sync.types';
export declare class RedisSyncExtension<TCE extends CustomEvents> implements Extension {
    priority: number;
    private readonly pub;
    private sub;
    private readonly pack;
    private readonly unpack;
    private originSockets;
    private locks;
    private lockPromises;
    private proxySockets;
    private readonly prefix;
    private readonly lockPrefix;
    private readonly msgChannel;
    private readonly serverId;
    private readonly customEventTTL;
    private readonly lockTTL;
    private instance;
    private readonly customEvents;
    private replyIdCounter;
    private pendingReplies;
    constructor(configuration: Configuration<TCE>);
    private getKey;
    private closeProxy;
    private pongProxy;
    private handleProxyMessage;
    private getOrClaimLock;
    private getOrClaimLockThrottled;
    private handleRedisMessage;
    maintainLock(documentName: string): Promise<void>;
    releaseLock(documentName: string): Promise<number>;
    private handleEventLocally;
    handleEvent<TName extends Extract<keyof TCE, string>>(eventName: TName, documentName: string, payload: any): Promise<ReturnType<TCE[TName]>>;
    lockDocument(documentName: string): Promise<() => Promise<number>>;
    onSocketOpen(ws: BaseWebSocket, serializedHTTPRequest: SerializedHTTPRequest, context?: {}): void;
    onSocketMessage(ws: BaseWebSocket, serializedHTTPRequest: SerializedHTTPRequest, detachableMsg: ArrayBuffer): Promise<void>;
    onSocketClose(socketId: string, code?: number, reason?: ArrayBuffer): void;
    onConfigure({ instance }: onConfigurePayload): Promise<void>;
    onLoadDocument(data: onLoadDocumentPayload): Promise<void>;
    afterUnloadDocument(data: afterUnloadDocumentPayload): Promise<void>;
    onDestroy(): Promise<void>;
}
