export declare const AuditEvent: {
    readonly WORKSPACE_CREATED: "workspace.created";
    readonly WORKSPACE_UPDATED: "workspace.updated";
    readonly WORKSPACE_INVITE_CREATED: "workspace.invite_created";
    readonly WORKSPACE_INVITE_RESENT: "workspace.invite_resent";
    readonly WORKSPACE_INVITE_REVOKED: "workspace.invite_revoked";
    readonly USER_CREATED: "user.created";
    readonly USER_DELETED: "user.deleted";
    readonly USER_LOGIN: "user.login";
    readonly USER_LOGOUT: "user.logout";
    readonly USER_ROLE_CHANGED: "user.role_changed";
    readonly USER_PASSWORD_CHANGED: "user.password_changed";
    readonly USER_PASSWORD_RESET: "user.password_reset";
    readonly USER_UPDATED: "user.updated";
    readonly USER_DEACTIVATED: "user.deactivated";
    readonly USER_ACTIVATED: "user.activated";
    readonly API_KEY_CREATED: "api_key.created";
    readonly API_KEY_UPDATED: "api_key.updated";
    readonly API_KEY_DELETED: "api_key.deleted";
    readonly SCIM_TOKEN_CREATED: "scim_token.created";
    readonly SCIM_TOKEN_UPDATED: "scim_token.updated";
    readonly SCIM_TOKEN_DELETED: "scim_token.deleted";
    readonly SPACE_CREATED: "space.created";
    readonly SPACE_UPDATED: "space.updated";
    readonly SPACE_DELETED: "space.deleted";
    readonly SPACE_MEMBER_ADDED: "space.member_added";
    readonly SPACE_MEMBER_REMOVED: "space.member_removed";
    readonly SPACE_MEMBER_ROLE_CHANGED: "space.member_role_changed";
    readonly GROUP_CREATED: "group.created";
    readonly GROUP_UPDATED: "group.updated";
    readonly GROUP_DELETED: "group.deleted";
    readonly GROUP_MEMBER_ADDED: "group.member_added";
    readonly GROUP_MEMBER_REMOVED: "group.member_removed";
    readonly COMMENT_CREATED: "comment.created";
    readonly COMMENT_DELETED: "comment.deleted";
    readonly COMMENT_UPDATED: "comment.updated";
    readonly COMMENT_RESOLVED: "comment.resolved";
    readonly COMMENT_REOPENED: "comment.reopened";
    readonly PAGE_CREATED: "page.created";
    readonly PAGE_TRASHED: "page.trashed";
    readonly PAGE_DELETED: "page.deleted";
    readonly PAGE_RESTORED: "page.restored";
    readonly PAGE_MOVED_TO_SPACE: "page.moved_to_space";
    readonly PAGE_DUPLICATED: "page.duplicated";
    readonly PAGE_RESTRICTED: "page.restricted";
    readonly PAGE_RESTRICTION_REMOVED: "page.restriction_removed";
    readonly PAGE_PERMISSION_ADDED: "page.permission_added";
    readonly PAGE_PERMISSION_REMOVED: "page.permission_removed";
    readonly PAGE_VERIFICATION_CREATED: "page.verification_created";
    readonly PAGE_VERIFICATION_UPDATED: "page.verification_updated";
    readonly PAGE_VERIFICATION_REMOVED: "page.verification_removed";
    readonly PAGE_VERIFIED: "page.verified";
    readonly PAGE_APPROVAL_REQUESTED: "page.approval_requested";
    readonly PAGE_APPROVAL_REJECTED: "page.approval_rejected";
    readonly PAGE_MARKED_OBSOLETE: "page.marked_obsolete";
    readonly SHARE_CREATED: "share.created";
    readonly SHARE_DELETED: "share.deleted";
    readonly PAGE_IMPORTED: "page.imported";
    readonly PAGE_EXPORTED: "page.exported";
    readonly SPACE_EXPORTED: "space.exported";
    readonly SSO_PROVIDER_CREATED: "sso.provider_created";
    readonly SSO_PROVIDER_UPDATED: "sso.provider_updated";
    readonly SSO_PROVIDER_DELETED: "sso.provider_deleted";
    readonly USER_MFA_ENABLED: "user.mfa_enabled";
    readonly USER_MFA_DISABLED: "user.mfa_disabled";
    readonly USER_MFA_BACKUP_CODE_GENERATED: "user.mfa_backup_code_generated";
    readonly LICENSE_ACTIVATED: "license.activated";
    readonly LICENSE_REMOVED: "license.removed";
    readonly ATTACHMENT_UPLOADED: "attachment.uploaded";
};
export type AuditEventType = (typeof AuditEvent)[keyof typeof AuditEvent];
export declare const EXCLUDED_AUDIT_EVENTS: Set<string>;
export declare const AuditResource: {
    readonly WORKSPACE: "workspace";
    readonly USER: "user";
    readonly PAGE: "page";
    readonly SPACE: "space";
    readonly SPACE_MEMBER: "space_member";
    readonly GROUP: "group";
    readonly COMMENT: "comment";
    readonly SHARE: "share";
    readonly API_KEY: "api_key";
    readonly SCIM_TOKEN: "scim_token";
    readonly SSO_PROVIDER: "sso_provider";
    readonly WORKSPACE_INVITATION: "workspace_invitation";
    readonly ATTACHMENT: "attachment";
    readonly LICENSE: "license";
};
export type AuditResourceType = (typeof AuditResource)[keyof typeof AuditResource];
export type ActorType = 'user' | 'system' | 'api_key';
export interface AuditLogPayload {
    event: AuditEventType;
    resourceType: AuditResourceType;
    resourceId?: string;
    spaceId?: string;
    changes?: {
        before?: Record<string, any>;
        after?: Record<string, any>;
    };
    metadata?: Record<string, any>;
}
export interface AuditLogData extends AuditLogPayload {
    workspaceId: string;
    actorId?: string;
    actorType: ActorType;
    ipAddress?: string;
    userAgent?: string;
}
