import { GroupService } from './services/group.service';
import { CreateGroupDto } from './dto/create-group.dto';
import { GroupUserService } from './services/group-user.service';
import { GroupIdDto } from './dto/group-id.dto';
import { PaginationOptions } from "../../database/pagination/pagination-options";
import { AddGroupUserDto } from './dto/add-group-user.dto';
import { RemoveGroupUserDto } from './dto/remove-group-user.dto';
import { UpdateGroupDto } from './dto/update-group.dto';
import { User, Workspace } from "../../database/types/entity.types";
import WorkspaceAbilityFactory from '../casl/abilities/workspace-ability.factory';
export declare class GroupController {
    private readonly groupService;
    private readonly groupUserService;
    private readonly workspaceAbility;
    constructor(groupService: GroupService, groupUserService: GroupUserService, workspaceAbility: WorkspaceAbilityFactory);
    getWorkspaceGroups(pagination: PaginationOptions, user: User, workspace: Workspace): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        description: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        name: string;
        scimExternalId: string;
        isDefault: boolean;
        isExternal: boolean;
    }>>;
    getGroup(groupIdDto: GroupIdDto, user: User, workspace: Workspace): Promise<{
        description: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        name: string;
        scimExternalId: string;
        isDefault: boolean;
        isExternal: boolean;
    }>;
    createGroup(createGroupDto: CreateGroupDto, user: User, workspace: Workspace): Promise<{
        description: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        name: string;
        scimExternalId: string;
        isDefault: boolean;
        isExternal: boolean;
    }>;
    updateGroup(updateGroupDto: UpdateGroupDto, user: User, workspace: Workspace): Promise<{
        description: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        name: string;
        scimExternalId: string;
        isDefault: boolean;
        isExternal: boolean;
    }>;
    getGroupMembers(groupIdDto: GroupIdDto, pagination: PaginationOptions, user: User, workspace: Workspace): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        password: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        role: string;
        name: string;
        settings: import("../../database/types/db").JsonValue;
        email: string;
        invitedById: string;
        avatarUrl: string;
        deactivatedAt: Date;
        emailVerifiedAt: Date;
        lastActiveAt: Date;
        lastLoginAt: Date;
        locale: string;
        hasGeneratedPassword: boolean;
        scimExternalId: string;
        timezone: string;
    }, undefined>>;
    addGroupMember(addGroupUserDto: AddGroupUserDto, user: User, workspace: Workspace): Promise<void>;
    removeGroupMember(removeGroupUserDto: RemoveGroupUserDto, user: User, workspace: Workspace): Promise<void>;
    deleteGroup(groupIdDto: GroupIdDto, user: User, workspace: Workspace): Promise<void>;
}
