import { CommentService } from './comment.service';
import { CreateCommentDto } from './dto/create-comment.dto';
import { UpdateCommentDto } from './dto/update-comment.dto';
import { PageIdDto, CommentIdDto } from './dto/comments.input';
import { PaginationOptions } from "../../database/pagination/pagination-options";
import { User, Workspace } from "../../database/types/entity.types";
import SpaceAbilityFactory from '../casl/abilities/space-ability.factory';
import { PageRepo } from "../../database/repos/page/page.repo";
import { CommentRepo } from "../../database/repos/comment/comment.repo";
import { PageAccessService } from '../page/page-access/page-access.service';
import { IAuditService } from '../../integrations/audit/audit.service';
import { WsService } from '../../ws/ws.service';
export declare class CommentController {
    private readonly commentService;
    private readonly commentRepo;
    private readonly pageRepo;
    private readonly spaceAbility;
    private readonly pageAccessService;
    private readonly wsService;
    private readonly auditService;
    constructor(commentService: CommentService, commentRepo: CommentRepo, pageRepo: PageRepo, spaceAbility: SpaceAbilityFactory, pageAccessService: PageAccessService, wsService: WsService, auditService: IAuditService);
    create(createCommentDto: CreateCommentDto, user: User, workspace: Workspace): Promise<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        spaceId: string;
        pageId: string;
        editedAt: Date;
        lastEditedById: string;
        parentCommentId: string;
        resolvedAt: Date;
        resolvedById: string;
        selection: string;
    }>;
    findPageComments(input: PageIdDto, pagination: PaginationOptions, user: User): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        spaceId: string;
        pageId: string;
        editedAt: Date;
        lastEditedById: string;
        parentCommentId: string;
        resolvedAt: Date;
        resolvedById: string;
        selection: string;
    }>>;
    findOne(input: CommentIdDto, user: User): Promise<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        spaceId: string;
        pageId: string;
        editedAt: Date;
        lastEditedById: string;
        parentCommentId: string;
        resolvedAt: Date;
        resolvedById: string;
        selection: string;
    }>;
    update(dto: UpdateCommentDto, user: User, workspace: Workspace): Promise<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        spaceId: string;
        pageId: string;
        editedAt: Date;
        lastEditedById: string;
        parentCommentId: string;
        resolvedAt: Date;
        resolvedById: string;
        selection: string;
    }>;
    delete(input: CommentIdDto, user: User, workspace: Workspace): Promise<void>;
}
