import { LicenseCheckService } from '../../../integrations/environment/license-check.service';
import { UserSessionRepo } from "../../../database/repos/session/user-session.repo";
import { CreateWorkspaceDto } from '../dto/create-workspace.dto';
import { UpdateWorkspaceDto } from '../dto/update-workspace.dto';
import { SpaceService } from '../../space/services/space.service';
import { UserRole } from '../../../common/helpers/types/permission';
import { SpaceMemberService } from '../../space/services/space-member.service';
import { WorkspaceRepo } from "../../../database/repos/workspace/workspace.repo";
import { KyselyDB, KyselyTransaction } from "../../../database/types/kysely.types";
import { User } from "../../../database/types/entity.types";
import { GroupUserRepo } from "../../../database/repos/group/group-user.repo";
import { GroupRepo } from "../../../database/repos/group/group.repo";
import { PaginationOptions } from "../../../database/pagination/pagination-options";
import { UpdateWorkspaceUserRoleDto } from '../dto/update-workspace-user-role.dto';
import { UserRepo } from "../../../database/repos/user/user.repo";
import { EnvironmentService } from '../../../integrations/environment/environment.service';
import { DomainService } from '../../../integrations/environment/domain.service';
import { Queue } from 'bullmq';
import { CursorPaginationResult } from "../../../database/pagination/cursor-pagination";
import { ShareRepo } from "../../../database/repos/share/share.repo";
import { WatcherRepo } from "../../../database/repos/watcher/watcher.repo";
import { FavoriteRepo } from "../../../database/repos/favorite/favorite.repo";
import { IAuditService } from '../../../integrations/audit/audit.service';
export declare class WorkspaceService {
    private workspaceRepo;
    private spaceService;
    private spaceMemberService;
    private groupRepo;
    private groupUserRepo;
    private userRepo;
    private environmentService;
    private domainService;
    private licenseCheckService;
    private shareRepo;
    private watcherRepo;
    private favoriteRepo;
    private readonly db;
    private attachmentQueue;
    private billingQueue;
    private aiQueue;
    private readonly auditService;
    private userSessionRepo;
    private readonly logger;
    constructor(workspaceRepo: WorkspaceRepo, spaceService: SpaceService, spaceMemberService: SpaceMemberService, groupRepo: GroupRepo, groupUserRepo: GroupUserRepo, userRepo: UserRepo, environmentService: EnvironmentService, domainService: DomainService, licenseCheckService: LicenseCheckService, shareRepo: ShareRepo, watcherRepo: WatcherRepo, favoriteRepo: FavoriteRepo, db: KyselyDB, attachmentQueue: Queue, billingQueue: Queue, aiQueue: Queue, auditService: IAuditService, userSessionRepo: UserSessionRepo);
    findById(workspaceId: string): Promise<{
        hostname: string;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        auditRetentionDays: number;
        trashRetentionDays: number;
        billingEmail: string;
        customDomain: string;
        defaultRole: string;
        defaultSpaceId: string;
        emailDomains: string[];
        enforceMfa: boolean;
        enforceSso: boolean;
        isScimEnabled: boolean;
        licenseKey: string;
        logo: string;
        name: string;
        plan: string;
        settings: import("../../../database/types/db").JsonValue;
        status: string;
        stripeCustomerId: string;
        trialEndAt: Date;
    }>;
    getWorkspaceInfo(workspaceId: string): Promise<{
        hostname: string;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        auditRetentionDays: number;
        trashRetentionDays: number;
        billingEmail: string;
        customDomain: string;
        defaultRole: string;
        defaultSpaceId: string;
        emailDomains: string[];
        enforceMfa: boolean;
        enforceSso: boolean;
        isScimEnabled: boolean;
        licenseKey: string;
        logo: string;
        name: string;
        plan: string;
        settings: import("../../../database/types/db").JsonValue;
        status: string;
        stripeCustomerId: string;
        trialEndAt: Date;
    }>;
    getWorkspacePublicData(workspaceId: string): Promise<{
        hostname: string;
        id: string;
        enforceSso: boolean;
        logo: string;
        name: string;
        authProviders: {
            id: string;
            type: string;
            name: string;
        }[];
    }>;
    create(user: User, createWorkspaceDto: CreateWorkspaceDto, trx?: KyselyTransaction): Promise<{
        hostname: string;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        auditRetentionDays: number;
        trashRetentionDays: number;
        billingEmail: string;
        customDomain: string;
        defaultRole: string;
        defaultSpaceId: string;
        emailDomains: string[];
        enforceMfa: boolean;
        enforceSso: boolean;
        isScimEnabled: boolean;
        licenseKey: string;
        logo: string;
        name: string;
        plan: string;
        settings: import("../../../database/types/db").JsonValue;
        status: string;
        stripeCustomerId: string;
        trialEndAt: Date;
    }>;
    addUserToWorkspace(userId: string, workspaceId: string, assignedRole?: UserRole, trx?: KyselyTransaction): Promise<void>;
    update(workspaceId: string, updateWorkspaceDto: UpdateWorkspaceDto): Promise<{
        hostname: string;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        auditRetentionDays: number;
        trashRetentionDays: number;
        billingEmail: string;
        customDomain: string;
        defaultRole: string;
        defaultSpaceId: string;
        emailDomains: string[];
        enforceMfa: boolean;
        enforceSso: boolean;
        isScimEnabled: boolean;
        logo: string;
        name: string;
        plan: string;
        settings: import("../../../database/types/db").JsonValue;
        status: string;
        stripeCustomerId: string;
        trialEndAt: Date;
    }>;
    getWorkspaceUsers(workspaceId: string, pagination: PaginationOptions): Promise<CursorPaginationResult<User>>;
    updateWorkspaceUserRole(authUser: User, userRoleDto: UpdateWorkspaceUserRoleDto, workspaceId: string): Promise<{
        password: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        role: string;
        name: string;
        settings: import("../../../database/types/db").JsonValue;
        email: string;
        invitedById: string;
        avatarUrl: string;
        deactivatedAt: Date;
        emailVerifiedAt: Date;
        lastActiveAt: Date;
        lastLoginAt: Date;
        locale: string;
        hasGeneratedPassword: boolean;
        scimExternalId: string;
        timezone: string;
    }>;
    generateHostname(name: string, trx?: KyselyTransaction): Promise<string>;
    checkHostname(hostname: string): Promise<{
        hostname: string;
    }>;
    deactivateUser(authUser: User, userId: string, workspaceId: string): Promise<void>;
    activateUser(authUser: User, userId: string, workspaceId: string): Promise<void>;
    deleteUser(authUser: User, userId: string, workspaceId: string): Promise<void>;
}
