/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiChatMessages {
  chatId: string;
  content: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  metadata: Json | null;
  role: string;
  toolCalls: Json | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
  workspaceId: string;
}

export interface AiChats {
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface ApiKeys {
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  lastUsedAt: Timestamp | null;
  name: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Attachments {
  aiChatId: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  fileExt: string;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  mimeType: string | null;
  pageId: string | null;
  spaceId: string | null;
  textContent: string | null;
  tsv: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Audit {
  actorId: string | null;
  actorType: Generated<string>;
  changes: Json | null;
  createdAt: Generated<Timestamp>;
  event: string;
  id: Generated<string>;
  ipAddress: string | null;
  metadata: Json | null;
  resourceId: string | null;
  resourceType: string;
  spaceId: string | null;
  workspaceId: string;
}

export interface AuthAccounts {
  authProviderId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AuthProviders {
  allowSignup: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  groupSync: Generated<boolean>;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  ldapBaseDn: string | null;
  ldapBindDn: string | null;
  ldapBindPassword: string | null;
  ldapConfig: Generated<Json | null>;
  ldapTlsCaCert: string | null;
  ldapTlsEnabled: Generated<boolean | null>;
  ldapUrl: string | null;
  ldapUserAttributes: Generated<Json | null>;
  ldapUserSearchFilter: string | null;
  name: string;
  oidcClientId: string | null;
  oidcClientSecret: string | null;
  oidcIssuer: string | null;
  samlCertificate: string | null;
  samlUrl: string | null;
  settings: Generated<Json | null>;
  type: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Backlinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  sourcePageId: string;
  targetPageId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Billing {
  amount: Int8 | null;
  billingScheme: string | null;
  cancelAt: Timestamp | null;
  cancelAtPeriodEnd: boolean | null;
  canceledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: string | null;
  deletedAt: Timestamp | null;
  endedAt: Timestamp | null;
  id: Generated<string>;
  interval: string | null;
  metadata: Json | null;
  periodEndAt: Timestamp | null;
  periodStartAt: Timestamp;
  planName: string | null;
  quantity: Int8 | null;
  status: string;
  stripeCustomerId: string | null;
  stripeItemId: string | null;
  stripePriceId: string | null;
  stripeProductId: string | null;
  stripeSubscriptionId: string;
  tieredFlatAmount: Int8 | null;
  tieredUnitAmount: Int8 | null;
  tieredUpTo: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface ChangeRequestEvents {
  actorId: string | null;
  changeRequestId: string;
  createdAt: Generated<Timestamp>;
  fromStatus: string | null;
  id: Generated<Int8>;
  metadata: Generated<Json | null>;
  reason: string | null;
  toStatus: string;
}

export interface ChangeRequests {
  approvedAt: Timestamp | null;
  approverId: string | null;
  closedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string;
  docVersion: string | null;
  dueDate: Timestamp | null;
  id: Generated<string>;
  impact: string;
  implementationNotes: string | null;
  implementerId: string | null;
  justification: string;
  pageId: string;
  priority: string;
  publishedAt: Timestamp | null;
  publishedVersionId: string | null;
  requestedAt: Generated<Timestamp>;
  requestedById: string;
  rowVersion: Generated<number>;
  serviceId: string;
  status: Generated<string>;
  techLeadId: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Comments {
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  editedAt: Timestamp | null;
  id: Generated<string>;
  lastEditedById: string | null;
  pageId: string;
  parentCommentId: string | null;
  resolvedAt: Timestamp | null;
  resolvedById: string | null;
  selection: string | null;
  spaceId: string;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DocopsAuditLogs {
  action: string;
  actorId: string | null;
  createdAt: Generated<Timestamp>;
  entityId: string;
  entityKind: string;
  id: Generated<Int8>;
  ip: string | null;
  payloadDiff: Json | null;
  userAgent: string | null;
}

export interface ExternalRefs {
  changeRequestId: string;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  fetchedMetadata: Json | null;
  id: Generated<string>;
  label: string | null;
  refType: string;
  url: string;
}

export interface Favorites {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  pageId: string | null;
  spaceId: string | null;
  templateId: string | null;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface FileTasks {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  errorMessage: string | null;
  fileExt: string | null;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  metadata: Json | null;
  pageId: string | null;
  source: string | null;
  spaceId: string | null;
  status: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Groups {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  isDefault: boolean;
  isExternal: Generated<boolean>;
  name: string;
  scimExternalId: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface GroupUsers {
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface KyselyMigrationDocops {
  name: string;
  timestamp: string;
}

export interface KyselyMigrationLockDocops {
  id: string;
  isLocked: Generated<number>;
}

export interface Labels {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  type: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Notifications {
  actorId: string | null;
  archivedAt: Timestamp | null;
  commentId: string | null;
  createdAt: Generated<Timestamp>;
  data: Json | null;
  emailedAt: Timestamp | null;
  id: Generated<string>;
  pageId: string | null;
  pageVerificationId: string | null;
  readAt: Timestamp | null;
  spaceId: string | null;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface Offices {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface PageAccess {
  accessLevel: string;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  id: Generated<string>;
  pageId: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface PageHistory {
  changeRequestId: string | null;
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  isPublishedVersion: Generated<boolean | null>;
  lastUpdatedById: string | null;
  pageId: string;
  publishedAt: Timestamp | null;
  publishedById: string | null;
  slug: string | null;
  slugId: string | null;
  spaceId: string;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  version: number | null;
  workspaceId: string;
}

export interface PageLabels {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  labelId: string;
  pageId: string;
}

export interface PagePermissions {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  groupId: string | null;
  id: Generated<string>;
  pageAccessId: string;
  role: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Pages {
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  crDraftId: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  currentPublishedVersionId: string | null;
  deletedAt: Timestamp | null;
  deletedById: string | null;
  icon: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  lastUpdatedById: string | null;
  parentPageId: string | null;
  position: string | null;
  slugId: string;
  spaceId: string;
  textContent: string | null;
  title: string | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
  ydoc: Buffer | null;
}

export interface PageTransclusionReferences {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  referencePageId: string;
  sourcePageId: string;
  transclusionId: string;
  workspaceId: string;
}

export interface PageTransclusions {
  content: Json;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  pageId: string;
  transclusionId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface PageVerifications {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  data: Json | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  mode: string | null;
  pageId: string;
  periodAmount: number | null;
  periodUnit: string | null;
  rejectedAt: Timestamp | null;
  rejectedById: string | null;
  rejectionComment: string | null;
  requestedAt: Timestamp | null;
  requestedById: string | null;
  spaceId: string;
  status: string | null;
  type: Generated<string>;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  verifiedById: string | null;
  workspaceId: string;
}

export interface PageVerifiers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  pageVerificationId: string;
  userId: string;
}

export interface ScimTokens {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  lastUsedAt: Timestamp | null;
  name: string;
  tokenHash: string;
  tokenLastFour: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Services {
  code: string;
  createdAt: Generated<Timestamp>;
  description: string | null;
  docVersion: Generated<string>;
  domain: string | null;
  id: Generated<string>;
  lifecycleState: Generated<string>;
  metadata: Generated<Json | null>;
  name: string;
  ownerId: string;
  rootPageId: string | null;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ServiceTags {
  serviceId: string;
  tagId: string;
}

export interface Shares {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  includeSubPages: Generated<boolean | null>;
  key: string;
  pageId: string | null;
  searchIndexing: Generated<boolean | null>;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface SpaceMembers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  groupId: string | null;
  id: Generated<string>;
  role: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Spaces {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  defaultRole: Generated<string>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string | null;
  settings: Json | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
  workspaceId: string;
}

export interface Tags {
  id: Generated<string>;
  name: string;
}

export interface Templates {
  collaboratorIds: string[] | null;
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  spaceId: string | null;
  textContent: string | null;
  title: string | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
  ydoc: Buffer | null;
}

export interface UserMfa {
  backupCodes: string[] | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isEnabled: Generated<boolean | null>;
  method: Generated<string>;
  secret: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface Users {
  authProvider: Generated<string | null>;
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  deactivatedAt: Timestamp | null;
  deletedAt: Timestamp | null;
  docopsRoles: Generated<string[] | null>;
  email: string;
  emailVerifiedAt: Timestamp | null;
  externalId: string | null;
  hasGeneratedPassword: Generated<boolean>;
  id: Generated<string>;
  invitedById: string | null;
  lastActiveAt: Timestamp | null;
  lastLoginAt: Timestamp | null;
  locale: string | null;
  name: string | null;
  officeId: string | null;
  password: string | null;
  role: string | null;
  scimExternalId: string | null;
  settings: Json | null;
  timezone: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string | null;
}

export interface UserSessions {
  createdAt: Generated<Timestamp>;
  deviceName: string | null;
  expiresAt: Timestamp;
  geoLocation: string | null;
  id: Generated<string>;
  ipAddress: string | null;
  lastActiveAt: Generated<Timestamp>;
  metadata: Json | null;
  revokedAt: Timestamp | null;
  userAgent: string | null;
  userId: string;
  workspaceId: string;
}

export interface UserTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  token: string;
  type: string;
  usedAt: Timestamp | null;
  userId: string;
  workspaceId: string | null;
}

export interface Watchers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  mutedAt: Timestamp | null;
  pageId: string | null;
  spaceId: string;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface WebhooksConfig {
  createdAt: Generated<Timestamp>;
  events: string[];
  id: Generated<string>;
  isActive: Generated<boolean>;
  name: string;
  secret: string;
  serviceId: string | null;
  url: string;
}

export interface WorkspaceInvitations {
  createdAt: Generated<Timestamp>;
  email: string | null;
  groupIds: string[] | null;
  id: Generated<string>;
  invitedById: string | null;
  role: string;
  token: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Workspaces {
  auditRetentionDays: Int8 | null;
  billingEmail: string | null;
  createdAt: Generated<Timestamp>;
  customDomain: string | null;
  defaultRole: Generated<string>;
  defaultSpaceId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  emailDomains: Generated<string[] | null>;
  enforceMfa: Generated<boolean | null>;
  enforceSso: Generated<boolean>;
  hostname: string | null;
  id: Generated<string>;
  isScimEnabled: Generated<boolean>;
  licenseKey: string | null;
  logo: string | null;
  name: string | null;
  plan: string | null;
  settings: Json | null;
  status: string | null;
  stripeCustomerId: string | null;
  trashRetentionDays: Int8 | null;
  trialEndAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  aiChatMessages: AiChatMessages;
  aiChats: AiChats;
  apiKeys: ApiKeys;
  attachments: Attachments;
  audit: Audit;
  authAccounts: AuthAccounts;
  authProviders: AuthProviders;
  backlinks: Backlinks;
  billing: Billing;
  changeRequestEvents: ChangeRequestEvents;
  changeRequests: ChangeRequests;
  comments: Comments;
  docopsAuditLogs: DocopsAuditLogs;
  externalRefs: ExternalRefs;
  favorites: Favorites;
  fileTasks: FileTasks;
  groups: Groups;
  groupUsers: GroupUsers;
  kyselyMigrationDocops: KyselyMigrationDocops;
  kyselyMigrationLockDocops: KyselyMigrationLockDocops;
  labels: Labels;
  notifications: Notifications;
  offices: Offices;
  pageAccess: PageAccess;
  pageHistory: PageHistory;
  pageLabels: PageLabels;
  pagePermissions: PagePermissions;
  pages: Pages;
  pageTransclusionReferences: PageTransclusionReferences;
  pageTransclusions: PageTransclusions;
  pageVerifications: PageVerifications;
  pageVerifiers: PageVerifiers;
  scimTokens: ScimTokens;
  services: Services;
  serviceTags: ServiceTags;
  shares: Shares;
  spaceMembers: SpaceMembers;
  spaces: Spaces;
  tags: Tags;
  templates: Templates;
  userMfa: UserMfa;
  users: Users;
  userSessions: UserSessions;
  userTokens: UserTokens;
  watchers: Watchers;
  webhooksConfig: WebhooksConfig;
  workspaceInvitations: WorkspaceInvitations;
  workspaces: Workspaces;
}
