import { UserService } from './user.service';
import { UpdateUserDto } from './dto/update-user.dto';
import { User, Workspace } from "../../database/types/entity.types";
import { WorkspaceRepo } from "../../database/repos/workspace/workspace.repo";
export declare class UserController {
    private readonly userService;
    private readonly workspaceRepo;
    constructor(userService: UserService, workspaceRepo: WorkspaceRepo);
    getUserInfo(authUser: User, workspace: Workspace): Promise<{
        user: {
            password: string;
            id: string;
            workspaceId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date;
            role: string;
            name: string;
            settings: import("../../database/types/db").JsonValue;
            email: string;
            invitedById: string;
            avatarUrl: string;
            deactivatedAt: Date;
            emailVerifiedAt: Date;
            lastActiveAt: Date;
            lastLoginAt: Date;
            locale: string;
            hasGeneratedPassword: boolean;
            scimExternalId: string;
            timezone: string;
        };
        workspace: {
            memberCount: number;
            hostname: string;
            description: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date;
            auditRetentionDays: number;
            trashRetentionDays: number;
            billingEmail: string;
            customDomain: string;
            defaultRole: string;
            defaultSpaceId: string;
            emailDomains: string[];
            enforceMfa: boolean;
            enforceSso: boolean;
            isScimEnabled: boolean;
            logo: string;
            name: string;
            plan: string;
            settings: import("../../database/types/db").JsonValue;
            status: string;
            stripeCustomerId: string;
            trialEndAt: Date;
        };
    }>;
    updateUser(updateUserDto: UpdateUserDto, user: User, workspace: Workspace): Promise<{
        password: string;
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        role: string;
        name: string;
        settings: import("../../database/types/db").JsonValue;
        email: string;
        invitedById: string;
        avatarUrl: string;
        deactivatedAt: Date;
        emailVerifiedAt: Date;
        lastActiveAt: Date;
        lastLoginAt: Date;
        locale: string;
        hasGeneratedPassword: boolean;
        scimExternalId: string;
        timezone: string;
    }>;
}
