name: Container

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t docmost:test .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: docmost:test
          format: table
          exit-code: "1"
          severity: CRITICAL,HIGH
          ignore-unfixed: true
