name: Container

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t docmost:test .
